spring.datasource.url=jdbc:postgresql://localhost:5432/iot_db
spring.datasource.username=myuser
spring.datasource.password=mysecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver
mybatis-plus.mapper-locations=classpath*:/mapper/**/*.xml
mybatis-plus.type-aliases-package=com.iot.datacollector.entity
mybatis-plus.configuration.map-underscore-to-camel-case=true
logging.level.com.iot.datacollector.mapper=debug
