apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/iot_db"
  SPRING_REDIS_HOST: "redis-service"
  MQTT_BROKER: "tcp://mosquitto-service:1883"
