spring.datasource.url=jdbc:postgresql://localhost:5432/iot_db
spring.datasource.username=myuser
spring.datasource.password=mysecretpassword
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# 邮件配置（使用你之前测试成功的）
spring.mail.host=smtp.qq.com
spring.mail.port=587
spring.mail.username=1127758625@qq.com
spring.mail.password=dcwrgmmytxhmgcfg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Redis 配置（周五用，现在可先不加）
spring.data.redis.host=localhost
spring.data.redis.port=6379

# 告警阈值
alert.temperature.threshold=30.0
